//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class faturadetay
    {
        public int id { get; set; }
        public string urun { get; set; }
        public Nullable<short> adet { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public Nullable<decimal> tutar { get; set; }
        public Nullable<int> faturaId { get; set; }
    
        public virtual faturabilgi faturabilgi { get; set; }
    }
}
