//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class teknikservisEntities : DbContext
    {
        public teknikservisEntities()
            : base("name=teknikservisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<arizadetay> arizadetay { get; set; }
        public virtual DbSet<cari> cari { get; set; }
        public virtual DbSet<departman> departman { get; set; }
        public virtual DbSet<faturabilgi> faturabilgi { get; set; }
        public virtual DbSet<faturadetay> faturadetay { get; set; }
        public virtual DbSet<gider> gider { get; set; }
        public virtual DbSet<kategori> kategori { get; set; }
        public virtual DbSet<notlar> notlar { get; set; }
        public virtual DbSet<personel> personel { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<urun> urun { get; set; }
        public virtual DbSet<urunhareket> urunhareket { get; set; }
        public virtual DbSet<urunkabul> urunkabul { get; set; }
        public virtual DbSet<uruntakip> uruntakip { get; set; }
        public virtual DbSet<iletisim> iletisim { get; set; }
    
        public virtual ObjectResult<urunkategori_Result> urunkategori()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<urunkategori_Result>("urunkategori");
        }
    }
}
