//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunkabul
    {
        public int id { get; set; }
        public Nullable<int> cariId { get; set; }
        public Nullable<int> personelId { get; set; }
        public Nullable<System.DateTime> gelistarih { get; set; }
        public Nullable<System.DateTime> cikistarih { get; set; }
        public string urunserino { get; set; }
    
        public virtual cari cari { get; set; }
        public virtual personel personel { get; set; }
    }
}
