//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunhareket
    {
        public int id { get; set; }
        public Nullable<int> urunId { get; set; }
        public Nullable<int> musteri { get; set; }
        public Nullable<int> personelId { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<short> adet { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public string urunserino { get; set; }
    
        public virtual cari cari { get; set; }
        public virtual personel personel { get; set; }
        public virtual urun urun { get; set; }
    }
}
